[platformio]
data_dir = web

[env:matrix-portal-s3]
platform = espressif32
board = adafruit_matrixportal_esp32s3
framework = arduino
build_src_filter = -<*> +<main.cpp>
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.flash_size = 8MB
board_build.partitions = default_8MB.csv
lib_deps =
    adafruit/Adafruit Protomatter@^1.7.0
    bblanchon/ArduinoJson@^7.0.4
    h2zero/NimBLE-Arduino@^2.2.0

build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1

[env:matrix-portal-m4-test]
platform = atmelsam
board = adafruit_matrix_portal_m4
framework = arduino
extra_scripts = pre:tools/generate_emoji_sprites.py
build_src_filter = -<*> +<m4_test.cpp>
monitor_speed = 115200
build_flags =
    -D SPIWIFI_SS=33
    -D SPIWIFI_ACK=31
    -D SPIWIFI_RESET=30
lib_deps =
    adafruit/Adafruit Protomatter@^1.7.0
    arduino-libraries/WiFiNINA@^1.8.14
    bblanchon/ArduinoJson@^7.0.4
